### ISSUE TITLE
DockerHub

### ISSUE THREAD

**Issue by nalomysouza** [iped-docker/iped#1]
Opa, atualizei a compilação e coloquei no [DockerHub](https://cloud.docker.com/repository/docker/nalomysouza/iped), contudo gostaria de adicionar o link deste repositório para mencioná-los já que vocês que criaram, você autoriza ?

Não achei outro, e demora bastante para compilar, por isso subi a versão 3.15.6

**Comment by atilaromero** [comment]
Claro

Em sáb, 11 de mai de 2019 11:04 AM, nalomysouza <notifications@github.com>
escreveu:
