### ISSUE TITLE
docker intermediary image with prerequisites

### ISSUE THREAD

**Issue by patrickdalla** [iped-docker/iped#11]
Hi,

I was maintaining a docker image with only IPED prerequisites programs, not with IPED itself. IPED was being referenced via network PATH. This was a better approach for easing IPED version updates.
I think you could keep a complete IPED docker image, but a intermediary image with all prerequisites would be appreciated.

**Comment by arisjr** [comment]
Nice idea!

I have implemented it in the latest release.

https://github.com/iped-docker/iped/releases/tag/4.0.7

Regards,
