### ISSUE TITLE
Graphical interface

### ISSUE THREAD

**Issue by patrickdalla** [iped-docker/iped#14]
As a enhancement suggestion: the graphical processing UI could be directed to a ssh connection on demand.

https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

I could do this using Xvfb: https://en.wikipedia.org/wiki/Xvfb

**Comment by arisjr** [comment]
Hello Patrick,

There's no need to change the docker to forward X sessions, only the container calling script. 

Have you taken a look on the script "dkr" on the read me of the project?
It has the commands to use a local graphic Xserver (you can put it on your .bashrc), but, as it is now, indeed fails to forward to a remote Xserver using ssh. 

For it to work it has to be added the .Xauthority file on the docker root home. 

Let's say, once you login on your ssh server
```
# ssh -XY user@sshserver
```
you can use the dkr script to automate things.

```
dkr () 
{
  xhost +
  docker run --rm -it -v "`pwd`":"`pwd`":Z \
          -e DISPLAY -e GDK_BACKEND \
          -e GDK_SCALE \
          -e SAL_USE_VCLPLUGIN=gen \
          -e GDK_DPI_SCALE \
          -e QT_DEVICE_PIXEL_RATIO \
          -e LANG=C.UTF-8 \
          -e LC_ALL=C.UTF-8 \
          -e NO_AT_BRIDGE=1 \
          --device /dev/dri \
          --device /dev/snd \
          -v /etc/localtime:/etc/localtime:ro \
          -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
          -v /home/user/.Xauthority:/root/.Xauthority "$@"
}
```
I've added the user .Xauthority on the script now. 

Then you can run

```
# dkr --net=host -v /CASES/:/CASES/ ipeddocker/iped java -jar /CASES/CASEDIR/IPED/iped/lib/iped-search-app.jar --nologfile
``` 
...and you will be able to forward your X connection to a remote ssh client. 

X sessions forwarded to a remote server are quite slow, specially over the internet and over VPNs, but it works anyway. 
I will update the dkr script to fulfill this need.  

I hope I helped you somehow or you were thinking on some other scenario?

Regards,
Aristeu


UPDATE: I forgot to add the --net=host

**Comment by arisjr** [comment]
Closing the issue due to no response and proposed correction.
