### ISSUE TITLE
IPED docker (Analysing)

### ISSUE THREAD

**Issue by paulobreim** [iped-docker/iped#15]
Is the syntax below, which is in the instructions, not from the pre-4.0 version?

 sudo dkr -v /mnt/evidences:/evidences \
           -v /mnt/ipedtmp:/mnt/ipedtmp \
           ipeddocker/iped java -jar \ 
           /evidences/test/iped-output/indexador/lib/iped-search-app.jar 

Wouldn't it be something like:
dkr ipeddocker/iped java -jar  /evidences/test/iped/lib/iped-search-app.jar

tks
Paulo

**Comment by arisjr** [comment]
You're right, Paulo, the ReadMe is outdated.

I'll correct this part. 

Regards, 
Aristeu
