### ISSUE TITLE
A bat or Power Shell script to run the container in Windows.

### ISSUE THREAD

**Issue by danpos** [iped-docker/iped#2]
In the instructions to run the iped-docker container is provided a shell script to set X11 server up. I would like to know if it's possible to give a bat or ps (Power Shell) script to run the container in Windows.

Thanks in advance,

**Comment by atilaromero** [comment]
I never tried to run the container in windows. Maybe it could be easier to just run it outside a container? If that would work for you, take a look at https://github.com/lfcnassif/IPED/releases

**Comment by danpos** [comment]
Hi, thanks for your reaction, appreciated! Indeed sure will run it with the appropriated version is more comfortable (and I used it for production), but the point is to test it out by using Docker in Windows.

**Comment by atilaromero** [comment]
I see, maybe the "--nogui" IPED option could help during the processing phase, to avoid the need of a graphical interface. Later, when you use the software to see the results you will surely need  graphicals. At least in my use case, I use docker to extract data but use the normal version to see results.
