### ISSUE TITLE
Configuração de saída

### ISSUE THREAD

**Issue by paulobreim** [iped-docker/iped#3]
dkr -v /mnt/sdb4/suspeito:/mnt/sdb4/suspeito/suspeito.dd \
    -v /mnt/ipedtmp:/mnt/ipedtmp \
    -v /mnt/optional_jars:/root/IPED/optional_jars \
    -v /mnt/led/:/mnt/led \
    -v /mnt/PhotoDNA:/mnt/PhotoDNA \
    -v /mnt/kff:/mnt/kff \
    ipeddocker/iped java  -jar iped.jar \
    --nologfile \
    -d /mnt/sdb4/suspeito/suspeito.dd \
    -o /mnt/sdc2/evidences/iped-output

Considerando comando acima, questiono:
1 - Para que serve a primeira linha:
-v /mnt/sdb4/suspeito:/mnt/sdb4/suspeito/suspeito.dd
se abaixo temos :
-d /mnt/sdb4/suspeito/suspeito.dd
Se não coloco a o :/mnt/sdb4/suspeito/suspeito.dd, da que não encontrou o arquivo.

Ao efetuar o processamento, no final não encontrava o arquivo /mnt/sdc2/evidences/iped-output que está no -o do iped.
Então coloquei pra rodar novamente e durante o processamento pesquisei o indexador e achei ele que está sendo gravado na lib do docker:
/var/lib/docker/devicemapper/mnt/908c38078139f6f9e4db21d3925042b7f713027ad5a6622e9a8d7545ec0a4d0b/rootfs/mnt/sdc2/evidences/iped-output/indexador. Ou seja, foi adicionado o path /var/lib/docker/devicemapper/mnt/908c38078139f6f9e4db21d3925042b7f713027ad5a6622e9a8d7545ec0a4d0b/rootfs

Tem algum manual ou algo que explique cada linha?

Paulo

**Comment by atilaromero** [comment]
O - v é  um parametro do docker. Ele monta pastadohost:pastanocontainer. Vc
nao esta usando o que vem antes do : igual ao que esta depois, eu recomendo
deixar igual. Por exemplo, na primeira linha vc esta montando uma pasta do
host em uma pasta do container com nome de arquivo. Em vez de chamar direto
o java, vc pode deletar tudo  de java em diante e chamar bash. Ou para
explorar, dkr ipeddocker/iped bash

Em seg, 14 de set de 2020 3:38 PM, Paulo Cesar Breim (PCB) <
notifications@github.com> escreveu:

**Comment by paulobreim** [comment]
OK, obrigado.
Alterei aqui e consegui rodar. Primeiro testei com a opção fastmode e foi até o fim, quando tiri a opção pra rodar pra valer tomei aquele erro JVM Crashes:
.# A fatal error has been detected by the Java Runtime Environment:
#
.#  SIGSEGV (0xb) at pc=0x00007fc239f138ee, pid=1, tid=0x00007fc23a61d700
.#
.# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
.# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)

que está descrito na wiki do iped.
Lá ele sugere para colocar true no robustImageReading  e no  enableExternalParsing.
Mas como é um docker, onde eu acesso esses arquivos?
Aliás e as demais opções de LocalConfig e IPEDConfig.

Não sei se estou rodando errado, o que estou fazendo é a partir da linha de comando do terminal linux eu executo:
source dkr.source e depois o equivalente ao exemplo do IPED docker (Processing), acho que seria isso porque na opção fastmode vai até o fim.

eu vi que executando o dkr ipeddocker/iped ele cai no prompt do root@82213340be66:~/IPED/iped-3.18.2# 
e lá tem os arquivos de configuração. Mas aí pra executar de dentro dessa pasta ele não enxerga as pastas do host.
Não entendi ainda direito como funciona.

Grato

**Comment by atilaromero** [comment]
O que está complicando é que são duas coisas novas ao mesmo tempo, o docker
e o iped. Acho que a chave aqui é entender como o docker monta os volumes,
de repente usando algum tutorial. Com os volumes vc consegue fazer ele
enxergar as pastas do host e dá para usar para sobrescrever os arquivos de
configuração do IPED.

Para poder ter uma pasta do host no container, dá para usar:
dkr -v /A/:/B/ ipeddocker/iped bash

Depois tenta criar arquivos na pasta /A do host e /B do container, para
testar como ele faz, para se habituar.

**Comment by paulobreim** [comment]
Achei um caminho, mas não sei se é o melhor. Fiz o seguinte:
Criei a pasta iped na raiz e um iped1.sh com:
dkr -v /mnt/sdb4/caso1:/mnt/sdb4/caso1 \
    -v /mnt/sdb4/caso1/optional_jars:/root/IPED/optional_jars \
    -v /mnt/sdb4/caso1/led/:/mnt/led \
    -v /mnt/sdb4/caso1/PhotoDNA:/mnt/PhotoDNA \
    -v /mnt/sdb4/caso1/kff:/mnt/kff \
    -v /mnt/sdb4/caso1/ipedtmp:/mnt/ipedtmp \
    -v /mnt/:/suspeito/ ipeddocker/iped bash
    
Essa última linha é a chave do acesso externo.
Estou dizendo que quando eu digitar, dentro do container, /suspeito, estou me referindo a pasta fora do container /mnt.
No container também tenho acesso a pasta /iped que foi onde criei o iped1.sh
Nessa mesma pasta /iped eu coloquei 3 arquivos de configuração (IPEDConfig.txt, AdvancedConfig.txt e LocalConfig.txt) porque pretendo usar esse arquivos no lugar dos que estão no container.
criei também o 2.sh que explico adiante.

Ai executei o dkr.source que está na documentação para acompanhar graficamente, sem alterações nele.
Em seguida executei o 1.sh
Ao fazer isso eu estarei dentro do prompt do container.
E dentro do container executei o /iped/2.sh que contém:
cp /iped/IPEDConfig.txt profiles/pt-BR/default/IPEDConfig.txt
cp /iped/AdvancedConfig.txt profiles/pt-BR/default/conf/AdvancedConfig.txt
cp /iped/LocalConfig.txt .
java -Xmx8G -jar iped.jar -d /suspeito/sdb4/caso1/caso1.dd -o /suspeito/sdb4/caso1/iped-output 

Com os comandos cp eu substitui os arquivos de configuração pelos que eu queria e na última linha eu executo o iped que vai usar os arquivos que estão no host na pasta /mnt/sdb4 e que dentro do container ele enxerga como /suspeito/sdb4.

Obviamente não estou me preocupando com otimização como onde vai ficar o arquivo tmp, etc. a ideia aqui é funcionar dentro do container.

O programa rodou, embora eu ainda tenha erros do java de erro de memória, que eu to tentando descobrir.

Fiz uma segunda configuração usando o docker-compose up que lê o arquivo de configuração docker-compose.yaml, e funcionou também, mas sem a visualização gráfica. Pra ela funcionar eu acho que tenho que dar um jeito de pegar o que esta no dkr.source e colocar dentro do docker-compose.yaml, mas ainda não consegui fazer isso.

**Comment by paulobreim** [comment]
entendido
