### ISSUE TITLE
Cannot process due to "No X11 DISPLAY variable set" even without --nogui option and Locale issue?

### ISSUE THREAD

**Issue by madsumm** [iped-docker/iped#4]
Hi,

After running the iped:processor docker, i keep failing due to the NO X11 DISAPLY Variable Set error.
After some diagnostics, before running the iped.jar, with interactive BASH session to your docker, is ran "export DISPLAY=:0.0"

However, I am still stuck as the system doesn't seem to be processing..

Also, the profile locale is defaulted to pt-BR, i need to manually change the LocalConfig.txt to en to enable English ingest?

**Comment by atilaromero** [comment]
Sorry to take so long to answer you, I missed the issue completely.
The "processor" tag does not have the required packages to show a graphical interface. The latest or 3.18.4._3 does, but it requires some extra options, like -e DISPLAY and -v /tmp/.X11-unix/:/tmp/.X11-unix/.
To process the image without using a graphical user interface, you have to use the option "--nogui". Another useful option is "--nologfile"
Here is a sample command that should work. It process the iped.jar as a input source:
docker run --rm -it ipeddocker/iped:processor java -jar iped.jar --nogui --nologfile -d /root/IPED/iped/iped.jar

**Comment by atilaromero** [comment]
In the latest tags, you can use the environment variable iped_locale=en to change the input language

**Comment by atilaromero** [comment]
The code that checked the available memory was trying to show a pop up warning about low memory. It is fixed in the IPED master, it will show a more informative message in the console. But in the meanwhile, the actual solution is to increase available memory. It will complain if it has less than 200MB per thread.
To decrease the number of threads, use docker run --rm **-e iped_numThreads=1** ...
And to increase the Java max heap, use docker run --rm -e iped_numThreads=1 ipeddocker/iped:processor java **-Xmx200m**

**Comment by mcquadenc** [comment]
I am having the same problem, even using the `--nogui --nologfile` attribute the error occurs.
I am using the version: Indexer and Digital Evidence Processor 3.18.4


However, in version 3.18.2 it works normally with the same command.

```
sudo docker run  -v $WORK_DIR:/evidences \
                 -v $TEMP_DIR:/mnt/ipedtmp \
                 --workdir /evidences \
                 ipeddocker/iped:processor java -jar /root/IPED/iped/iped.jar --nogui \
                 -d $DATA_DIR \
                 -o $OUTPUT_DIR
```

I think it's related to this [commit]( https://github.com/sepinf-inc/IPED/commit/4dca7367b91892c745d11658eee4b3dd96f094a4#diff-5289e920a2937606aeab04d943b928e637f7c175ea39dc53f586084c72e19528)

**Comment by arisjr** [comment]
It's a known issue that will probably be solved in a next release.

https://github.com/sepinf-inc/IPED/issues/381

Once it's released, it will be on the docker also.

Best regards,
Aristeu


Em qua., 17 de mar. de 2021 às 18:14, mcquadenc ***@***.***>
escreveu:

**Comment by atilaromero** [comment]
In the meanwhile, try to use *-e iped_numThreads=1*
ipeddocker/iped:processor java* -Xmx200m*

That's because the program may be trying to open a pop up just to warn
about low memory.

**Comment by mcquadenc** [comment]
Dear @atilaromero, you were right. The IPED was trying to show an error message as you said, like the following image:
[Image](https://linkpicture.com/q/Captura-de-Tela-2021-03-20-as-00.47.39.png)

However, for the unsuspecting, I was able to configure the docker for mac using GUI applications and I was able to view the blessed message. The same principles can be used for other platforms.

Follow the link with instructions:

[Docker for Mac and GUI applications](https://fredrikaverpil.github.io/2016/07/31/docker-for-mac-and-gui-applications/)

[X11 forwarding issues with release 10](https://forums.docker.com/t/x11-forwarding-issues-with-release-10/11252/3)

When I was able to view the message in the java popup window, IPED showed the error in the log, as follows:

```
2021-03-20 00:47:55	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
java.lang.Exception: Pouca memória disponível: menos de 200MB por thread de processamento.
Isso pode causar lentidão e erros de parsing de arquivos complexos.
	Utilize uma JVM x64 (preferencial), 
	aumente a memória da JVM via parâmetro -Xmx 
	ou diminua o parâmetro numThreads na configuração avançada.
	at dpf.sp.gpinf.indexer.process.Statistics.printSystemInfo(Statistics.java:323) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:187) ~[iped-engine-3.18.4.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:216) [iped.jar:?]
	at dpf.sp.gpinf.indexer.IndexFiles.doInBackground(IndexFiles.java:59) [iped.jar:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

ERROR!!!
```

Thanks

**Comment by paulobreim** [comment]
@mcquadenc  Did you install java x64b to solve this problem?

**Comment by arisjr** [comment]
Please, test the latest tag version.

It has an IPED update on this problem.

**Comment by arisjr** [comment]
Closing the issue. If another similar problem exists, please open another one.
