### ISSUE TITLE
/mnt/ipedtmp/ grows in size and breaks processing.

### ISSUE THREAD

**Issue by MariasStory** [iped-docker/iped#5]
Hi,

I am using docker image and see that the temp folder is growing in size and breaks processing:
252G /mnt/ipedtmp/
The processing stops because no space in root directory.

lfcnassif suggested to set the value:
indexTempOnSSD = false

Please refer to:
https://github.com/sepinf-inc/IPED/issues/385

Thank you

**Comment by MariasStory** [comment]
This change to the LocalConfig.txt did solve my problem.

**Comment by arisjr** [comment]
Hello,

The directory /mnt/ipedtmp should be mounted externally with -v, preferably
on a SSD drive.

Regards,.


Em ter., 9 de mar. de 2021 às 09:57, forensicator <notifications@github.com>
escreveu:
