### ISSUE TITLE
Upgrade to IPED-4.0.1

### ISSUE THREAD

**Issue by lfcnassif** [iped-docker/iped#8]
I think the 4.0.1 version is pretty stable and it also has fixes for some issues found in 3.x.

**Comment by arisjr** [comment]
I will try to release a new version this week.

**Comment by lfcnassif** [comment]
Don't hurry, take your time, no urgent need for this.

**Comment by lfcnassif** [comment]
Thanks

**Comment by arisjr** [comment]
The new container with 4.0.6 with most of the new IPED features is finally updated and tested!

Best regards!

**Comment by lfcnassif** [comment]
Thank you @arisjr!
